language: clojure
lein: lein2
before_script: "cd Jest"
script: "lein2 midje"
jdk:
  - openjdk7
branches:
  only:
    - dev
    - master
notifications:
  email:
    - bep-jest@googlegroups.com
    - wordempire@gmail.com